name: Deploy on stage

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit to deploy"
        default: ""
        
jobs:
  deploy:
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: site
        ref: ${{ inputs.commit }}

    - name: Copy configs
      run: ls site
